DROP TABLE IF EXISTS user_info;
CREATE TABLE user_info(
	id SERIAL,
	name VARCHAR(50) UNIQUE,
	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS cat;
CREATE TABLE cat(
	id SERIAL,
	name VARCHAR(50) UNIQUE,
	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS cat_weight;
CREATE TABLE cat_weight(
	id SERIAL,
	cat_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	weight_gram INTEGER NOT NULL,
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS cat_state;
CREATE TABLE cat_state(
	id SERIAL,
	cat_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	state_name VARCHAR(200) NOT NULL,
	val INTEGER,
	unit VARCHAR(20),
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS eat;
CREATE TABLE eat(
	id SERIAL,
	cat_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	food_id INTEGER NOT NULL,
	gram INTEGER NOT NULL,
	state INTEGER DEFAULT 3,
	description TEXT,
	eaten_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS food;
CREATE TABLE food(
	id SERIAL,
	name VARCHAR(100) NOT NULL,
	price INTEGER,
	img VARCHAR(100),
	url VARCHAR(255),
	gram INTEGER,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);